version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:7.0.3
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_DATABASE=mestodb
volumes:
  mongodb_data:
    driver: local